config/routes.rb
LeaveSystem::Application.routes.draw do
resource :authentication, :controller => "authentication" do
  member do
     match :login
     get :logout
     match :set_password
     match :forgot_password
     match :reset_password
  end
end

resources :employees, :controller => "employees" do
   member do
       put :update
       get :leave_balances
       get :my_leave_approvals
   end

   resources :leaves, :controller => "leaves"
end

end

app/models/employee.rb
require 'role_access'

class Employee < ActiveRecord::Base
include RoleAccess
  attr_accessible :local_addr, :perm_addr, :age, :designation, :dob, :doj, :emp_id, :first_name, :last_name, :manager_emp_id, :manager_name, :mob_no, :off_email_id, :pan_no, :pers_email_id, :phone_no, :gender, :roles
attr_accessible :leaves_attributes

#attr_protected :roles

validate :dates_cannot_be_in_the_future
validates_presence_of :local_addr, :message => "Local address cannot be blank"
validates_presence_of :perm_addr, :message => "Permanent address cannot be blank"
validates_presence_of :age, :message => "Unable to calculate employee's age at joining; please enter employee dob correctly.."
validates_presence_of :designation, :message => "Employee's designation at RapidThink cannot be blank"
validates_presence_of :dob, :message => "Employee's date of birth cannot be blank"
validates_presence_of :doj, :message => "Employee's date of joining RapidThink cannot be blank"
validates_presence_of :emp_id, :message => "Emp Id cannot be blank"
validates_presence_of :first_name, :message => "Employee's first name cannot be blank"
validates_presence_of :last_name, :message => "Employee's last name cannot be blank"
validates_presence_of :manager_emp_id, :message => "Employee's manager id cannot be blank"
validates_presence_of :manager_name, :message => "Employee's manager name cannot be blank"
validates_presence_of :mob_no, :message => "Employee's mobile number cannot be blank"
validates_presence_of :off_email_id, :message => "Employee's RapidThink email id cannot be blank"
validates_presence_of :pan_no, :message => "Employee's PAN number cannot be blank"
validates_presence_of :pers_email_id, :message => "Employee's personal email id cannot be blank"
validates_presence_of :phone_no, :message => "Employee's permanent phone no cannot be blank"
validates_presence_of :roles, :message => "Employee roles cannot be blank"
validates_presence_of :gender, :message => "Employee gender cannot be blank"

validates_uniqueness_of :emp_id, :message => "Employee id has to be unique, this emp id already exists!"
validates_uniqueness_of :mob_no, :message => "Employee mobile no has to be unique"
validates_uniqueness_of :pan_no, :message => "Employee PAN NO has to be unique"
validates_uniqueness_of :off_email_id, :message => "Employee's RapidThink email id should be unique"
validates_uniqueness_of :pers_email_id, :message => "Employee's personal email id should be unique"

validates_date :dob, :invalid_date_message => "Please enter a valid date for employee's date of birth"
validates_date :doj, :invalid_date_message => "Please enter a valid date for employee's date of joining RapidThink"


validates_length_of :mob_no, :is => 10, :message => "Mobile number entry should contain 10 digits"

validates_numericality_of :age, :only_integer => true, :greater_than_or_equal_to => 18, :message => "Employee should be greater than 18 years of age"
validates_numericality_of :emp_id, :only_integer => true,:greater_than_or_equal_to => 0, :message => "Please enter a positive integer for emp id"
validates_numericality_of :manager_emp_id, :only_integer => true,:greater_than_or_equal_to => 0, :message => "Please enter a positive integer for manager emp id"
validates_numericality_of :mob_no, :only_integer => true, :greater_than_or_equal_to => 0, :message => "Please enter a valid numerical value for employee's mobile no"
validates_numericality_of :phone_no, :only_integer => true, :greater_than_or_equal_to => 0, :message => " Please enter a valid numerical value for employee's phone no"


validates_format_of :off_email_id,
                      :with => /^([^@\s]+)@((?:[-a-zA-Z0-9]+\.)+[a-zA-Z]{2,})$/,
                      :message => 'Employee\'s official email id must have a valid format, e.g. a@b.com'

validates_format_of :pers_email_id,
                      :with => /^([^@\s]+)@((?:[-a-zA-Z0-9]+\.)+[a-zA-Z]{2,})$/,
                      :message => 'Employee\' personal email id must have a valid format, e.g. a@b.com'


has_many :leaves, :class_name => 'Leave', :foreign_key => 'employee_id'
has_one :user, :dependent => :destroy
has_many :subordinates, :class_name => "Employee", :foreign_key => "manager_emp_id"
belongs_to :manager, :class_name => "Employee"

accepts_nested_attributes_for :leaves

def self.search(search)
   if search
    if search.is_i?
      where('emp_id = ?', "#{search.to_i}")
    elsif search.is_a?(String)
       where('last_name LIKE ? or first_name LIKE ? or designation LIKE ?', "%#{search}%" , "%#{search}%", "%#{search}%")
    end
   else
       scoped
   end
end


def dates_cannot_be_in_the_future
       errors.add(:doj,"Joining date cannot be in the future") if 
       (!doj.blank? and doj > Date.today) 
       errors.add(:dob,"Date of birth cannot be in the future") if
       (!dob.blank? and dob > Date.today)
end

def find_leave_approver
emp=self
    while (1) do
          if emp.manager.is_leave_approver?
              manager=emp.manager
              #ActiveRecord::Base.logger.info("The manager now is: #{manager.last_name}, #{manager.emp_id}")
              return manager
           else
              emp=emp.manager
          end
    end
end

def manager
    Employee.find_by_emp_id(self.manager_emp_id)
end


end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
layout 'employee'

  def new
    @employee=Employee.new
  end

  def create
     @employee=Employee.new
     @employee.designation=params[:employee][:designation]
     @employee.emp_id=params[:employee][:emp_id]
     @employee.doj=params[:employee][:doj]
     @employee.manager_name=params[:employee][:manager_name]
     @employee.manager_emp_id=params[:employee][:manager_emp_id]
     @employee.roles=params[:employee][:roles]
     @employee.last_name=params[:employee][:last_name]
     @employee.first_name=params[:employee][:first_name]
     @employee.mob_no=params[:employee][:mob_no]
     @employee.phone_no=params[:employee][:phone_no]
     @employee.dob=params[:employee][:dob]
     @employee.age=params[:employee][:age]
     @employee.address=params[:employee][:address]
     @employee.pan_no=params[:employee][:pan_no]
     @employee.off_email_id=params[:employee][:off_email_id]
     @employee.pers_email_id=params[:employee][:pers_email_id]
     if @employee.save
          flash[:notice] = "New employee #{@employee.emp_id} was created!"
          redirect_to employee_path(@employee)
     else
          flash[:errors]=@employee.errors
          render :action => "new"
     end
  end
 

  def hub
  end

  def leave_balances
  end

  def show
  end

end

app/controllers/employees_controller.rb
require 'will_paginate/array'
class EmployeesController < ApplicationController
include Utilities
layout 'employee'

before_filter :login_required
before_filter :find_logged_emp
before_filter :find_user_id

 def new
    @employee=Employee.new
    @user=User.new
    4.times {@employee.leaves.build}
 end

 def index
     #@employees=Employee.all.paginate(:page => params[:page], :per_page => 5)
     @employees=Employee.search(params[:search]).paginate(:page => params[:page], :per_page => 5)
 end

  def create
     @employee=Employee.new
     @user=User.new
     @user.login=params[:employee][:emp_id]
     @user.email=params[:employee][:off_email_id]
     @employee=Employee.new(params[:employee])
     params[:employee][:roles].delete("") 
     if !params[:employee][:roles].empty?
        tmproles=params[:employee][:roles]
     else
        tmproles=[].push(Role::None.id)
     end
     @employee.roles = Role.find_all(*tmproles.map(&:to_i))
     @employee.age=@employee.doj.year-@employee.dob.year
     @user.employee=@employee
     Rails.logger.info("The mob no is: #{@employee.mob_no}")
     if @employee.save && @user.save
         flash[:notice] = "New employee with emp id: #{@employee.emp_id} was successfully created!"
         Notifications.welcome(@user).deliver
         redirect_to employee_path(@employee)
     else
          Rails.logger.info("The errors are: #{@employee.errors.full_messages}")
          flash[:errors]=(@employee.errors)
          #redirect_to new_employee_path
          render :action => "new"
     end
  end
 

 
  def leave_balances
  end


  def show
       @employee=Employee.find(params[:id])
       Rails.logger.info("This employees gender is :#{@employee.gender}")
       render :action => 'show', :layout => '/layouts/employee'
  end


  def edit
      @employee=Employee.find(params[:id])
      @employee.leaves.where('admin_comments=?','Initial Credit').build
  end

  def update
     @employee=Employee.find(params[:id])
     
     params[:employee][:roles].delete("") 
     if !params[:employee][:roles].empty?
        tmproles=params[:employee][:roles]
     else
        tmproles=[].push(Role::None.id)
     end
     @employee.update_attributes(params[:employee])
     @employee.roles = Role.find_all(*tmproles.map(&:to_i))
     @employee.age=@employee.doj.year-@employee.dob.year
     
     if @employee.save
         Rails.logger.info("The updated mob no is: #{@employee.mob_no}")
         flash[:notice] = "Employee with emp id: #{@employee.emp_id} was successfully updated!"
         redirect_to employee_path(@employee)
     else
         flash[:errors]=@employee.errors
         Rails.logger.info("The errors in update are: #{@employee.errors.each{|i,j| j}}")
         #redirect_to new_employee_path
         render :action => "edit"
     end
 end


  def my_leave_approvals
     @leaves=Leave.find_by_approver_emp_id(current_emp.emp_id)
  end
   
  def delete
  end

  def destroy
  end


  def find_logged_emp
      @emp=current_emp
  end

  def find_user_id
      @uid=current_user_id
  end
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_edit_employee_details.html.erb
<%= form_for @employee, :url => employee_path(@employee), :html => {:class => "emp_form"} do |f| -%>

<fieldset id="new_emp_pers_detail">

<h4>Personal Details</h4>

  <label for="employee_last_name">Last name</label>
  <%= f.text_field :last_name, :size=>'15',:maxlength =>'100' %><br/><br/>

  <label for="employee_first_name">First name</label>
  <%= f.text_field :first_name, :size=>'15',:maxlength =>'100' %><br/><br/>

  <label for="employee_dob">Date of birth</label>
  <%= f.date_select :dob, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true, :start_year => 1900, :end_year => Date.today.year %><br/><br/>

  <label for="employee_gender">Gender</label>
  <%= f.radio_button :gender, "Male" %> 
  <label for="employee_gender_male" id="emp_gender_male">Male</label>
  <%= f.radio_button :gender, "Female" %>
  <label for="employee_gender_female" id="emp_gender_female">Female</label>

  <br/><br/><br/>

  <label for="emp_local_addr">Local address</label>
  <%= f.text_area :local_addr, :cols => 15, :rows => 5, :maxlength =>'500' %><br/><br/>

  <label for="emp_perm_addr">Permanent address</label>
  <%= f.text_area :perm_addr, :cols => 15, :rows => 5, :maxlength =>'500' %><br/>
  
  <label for="same_as_local_addr">Same as local addr</label>
<!--  <input id="copy_addr" name="copy_addr" type="checkbox" value="0"/><br><br/> -->

  <%= check_box_tag 'copy_addr',{},@employee.local_addr==@employee.perm_addr%><br/><br/>

 
  <label for="employee_mobile">Mobile no</label>
  <%= f.text_field :mob_no, :size=>'15' %><br/><br/>

  <label for="employee_phone">Phone no</label>
  <%= f.text_field :phone_no, :size=>'15' %><br/><br/>


  <label for="employee_pan">PAN no</label>
  <%= f.text_field :pan_no, :size=>'15' %><br/><br/>

  <label for="pers_email_id">Personal email</label>
  <%= f.text_field :pers_email_id, :size=>'15', :maxlength=>'100' %><br/><br/>

</fieldset>

<fieldset id="new_emp_emp_detail">
<h4>Professional Details</h4>

  <label for="employee_id">Emp id</label>
  <%= f.text_field :emp_id, :size=>'15' %><br/><br/>

  <label for="employee_designation">Designation</label>
  <%= f.text_field :designation, :size=>'15',:maxlength =>'100' %><br/><br/>

  <label for="employee_doj">Date of joining</label>
  <%= f.date_select :doj, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true,:start_year => 1900, :end_year => Date.today.year %><br/><br/>

  <label for="manager_emp_id">Manager's emp id</label>
  <%= f.text_field :manager_emp_id, :size=>'15' %><br/><br/>

  <label for="manager_name">Manager's name</label>
  <%= f.text_field :manager_name, :size=>'15',:maxlength =>'100' %><br/><br/>


  <label for="off_email_id">RapidThink email</label>
  <%= f.text_field :off_email_id, :size=>'15', :maxlength =>'100' %><br/><br/>

  <% 
      @roles=[]
      @roles.push(['None',0])
      @roles.push(['Admin',1])
      @roles.push(['Leave Approver',2])
      selected_roles=@employee.roles.collect{|i| i.id}.flatten

  %>

   <label for="roles">Roles</label>
   <%= f.select :roles, options_for_select(@roles, :selected => selected_roles, :disabled => @roles[0][1]), {}, {:multiple => true}  %><br/><br/>
  

<div class="buttons">
	<input type="submit" name="commit" value="Update Employee" class="button_large" tabindex="8"> 
	<!--<input type="reset" name="cancel" value="Cancel" class="button_large" tabindex="9">-->
</div>

</fieldset>


<% end %>

app/views/employees/_emp_home.html.erb
<% content_for(:page_heading, "Employee Home") -%>
<% content_for :emp_home do -%>
<div id="leave_links">
 <ul id="emp_leave_links">
  <%#= content_tag('li',link_to("My Balances",leave_balances_employee_path(current_user)))%><br/><br/>
  <%= content_tag('li',link_to("My Leaves","http://www.google.com"),:class => yield(:my_leave_history_selected))%><br/><br/>
  <%= content_tag('li',link_to("My Approvals",my_leave_approvals_employee_path(@uid)))%><br/><br/>
  <%= content_tag('li',link_to("New Leave Request",new_employee_leafe_path(@uid)))%><br/><br/>
  <%= content_tag('li',link_to("Holiday List","http://www.google.com"),:class => yield(:current_holiday_list_selected))%><br/><br/>
  <%= content_tag('li',link_to("Modify Holidays","http://www.google.com"),:class => yield(:current_holiday_list_selected))%><br/><br/>
  <%= content_tag('li',link_to("RapidThink Employees",employees_path))%><br/><br/>
  <%= content_tag('li',link_to("New Employee",new_employee_path))%><br/><br/>
 </ul>
</div>
<% end %>

<%= render :file => 'layouts/_emp_hub' %>

app/views/employees/_employee_details.html.erb
<%= form_for @employee, :url => employees_path, :html => {:class => "emp_form"} do |f| -%>

<fieldset id="new_emp_pers_detail">

<h4>Personal Details</h4>

  <label for="employee_last_name">Last name</label>
  <%= f.text_field :last_name, :size=>'15',:maxlength =>'100' %><br/><br/>

  <label for="employee_first_name">First name</label>
  <%= f.text_field :first_name, :size=>'15',:maxlength =>'100' %><br/><br/>

  <label for="employee_dob">Date of birth</label>
  <%= f.date_select :dob, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true, :start_year => 1900 %><br/><br/>

  <label for="employee_gender">Gender</label>
  <%= f.radio_button :gender, "Male" %> 
  <label for="employee_gender_male" id="emp_gender_male">Male</label>
  <%= f.radio_button :gender, "Female" %>
  <label for="employee_gender_female" id="emp_gender_female">Female</label>

  <br/><br/>

  <label for="emp_local_addr">Local address</label>
  <%= f.text_area :local_addr, :cols => 15, :rows => 5, :maxlength =>'500' %><br/><br/>

  <label for="emp_perm_addr">Permanent address</label>
  <%= f.text_area :perm_addr, :cols => 15, :rows => 5, :maxlength =>'500' %><br/>
  <label for="same_as_local_addr">Same as local addr</label>
  <input id="copy_addr" name="copy_addr" type="checkbox" value="0"/><br><br/>

 
  <label for="employee_mobile">Mobile no</label>
  <%= f.text_field :mob_no, :size=>'15' %><br/><br/>

  <label for="employee_phone">Phone no</label>
  <%= f.text_field :phone_no, :size=>'15' %><br/><br/>


  <label for="employee_pan">PAN no</label>
  <%= f.text_field :pan_no, :size=>'15' %><br/><br/>

  <label for="pers_email_id">Personal email</label>
  <%= f.text_field :pers_email_id, :size=>'15', :maxlength=>'100' %><br/><br/>

</fieldset>

<fieldset id="new_emp_emp_detail">
<h4>Employment Details</h4>

  <label for="employee_id">Emp id</label>
  <%= f.text_field :emp_id, :size=>'15' %><br/><br/>

  <label for="employee_designation">Designation</label>
  <%= f.text_field :designation, :size=>'15',:maxlength =>'100' %><br/><br/>

  <label for="employee_doj">Date of joining</label>
  <%= f.date_select :doj, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true,:start_year => 1900 %><br/><br/>

  <label for="manager_emp_id">Manager's emp id</label>
  <%= f.text_field :manager_emp_id, :size=>'15' %><br/><br/>

  <label for="manager_name">Manager's name</label>
  <%= f.text_field :manager_name, :size=>'15',:maxlength =>'100' %><br/><br/>


  <label for="off_email_id">RapidThink email</label>
  <%= f.text_field :off_email_id, :size=>'15', :maxlength =>'100' %><br/><br/>

  <% 
      @roles=[]
      @roles.push(['None',0])
      @roles.push(['Admin',1])
      @roles.push(['Leave Approver',2])

  %>

   <label for="roles">Roles</label>
   <%= f.select :roles, options_for_select(@roles, :selected => @roles[0][1], :disabled => @roles[0][1]), {}, {:multiple => true}  %><br/><br/>
  
</fieldset>

<fieldset id="new_emp_leave_detail">
<h4>Joining Leave Credits</h4>
  <label for="CL">Casual Leaves</label>
  <%#= f.text_field :cl, :size=>'15' %><br/><br/>

  <label for="SL">Sick Leaves</label>
  <%#= f.text_field :sl, :size=>'15' %><br/><br/>

  <label for="EL">Earned Leaves</label>
  <%#= f.text_field :el, :size=>'15' %><br/><br/>

  <label for="OH">Optional Holidays</label>
  <%#= f.text_field :oh, :size=>'15' %><br/><br/>


<div class="buttons">
	<input type="submit" name="commit" value="Create Employee" class="button_large" tabindex="8"> 
	<!--<input type="reset" name="cancel" value="Cancel" class="button_large" tabindex="9">-->
</div>

</fieldset>


<% end %>

app/views/employees/_employees.html.erb
<table id="rt_employees">
    <tbody>
         <tr>
             <th>Emp id</th>
             <th>Lastname</th>
             <th>Firstname</th>
             <th>Date of Joining</th>
             <th>Designation</th>
             <th>Manager</th>
         </tr>
     <% @employees.each do |emp| %>
         <tr id="emp_<%=emp.emp_id%>">
           <td><%= link_to emp.emp_id, edit_employee_path(emp) %></td>
           <td><%=emp.last_name%></td>
           <td><%=emp.first_name%></td>
           <td><%=emp.doj.strftime("%d-%b-%Y")%></td>
           <td><%=emp.designation%></td>
           <td><%=link_to emp.manager_name, employee_path(Employee.find_by_emp_id(emp.manager_emp_id))%></td>
        </tr>
     <% end %>
   </tbody>
</table>


            
 

app/views/employees/_new_emp_leaves.html.erb
<%content_for(:page_title, "Leave Details")%>
<h4>Joining Leave Credits</h4>
  <!--<label for="CL">Casual Leaves</label>-->
  <%=l.select :leave_type, options_for_select([['CL',1],['EL',2],['SL',3],['OH',4]]) %>
  <%=l.text_field :no_of_days, :size=>'15' %> days <br/><br/>
  <%=l.hidden_field :start_date, :value => Date.today%>
  <%=l.hidden_field :end_date, :value => Date.today%>
  <%=l.hidden_field :admin_comments, :value => 'Initial Credit'%>
  <%=l.hidden_field :action, :value => 'Credit'%>

app/views/employees/_new_employee_details.html.erb
<%= form_for @employee, :url => employees_path, :html => {:class => "emp_form"} do |f| -%>

<fieldset id="new_emp_pers_detail">
<%content_for(:page_title, "Personal Details")%>
<h4>Personal Details</h4>
 
  <label for="employee_last_name">Last name</label>
  <%= f.text_field :last_name, :size=>'15',:maxlength =>'100' %><br/><br/>

  <label for="employee_first_name">First name</label>
  <%= f.text_field :first_name, :size=>'15',:maxlength =>'100' %><br/><br/>

  <label for="employee_dob">Date of birth</label>
  <%= f.date_select :dob, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true, :start_year => 1900, :end_year => Date.today.year %><br/><br/>

  <label for="employee_gender">Gender</label>
  <%= f.radio_button :gender, "Male" %> 
  <label for="employee_gender_male" id="emp_gender_male">Male</label>
  <%= f.radio_button :gender, "Female" %>
  <label for="employee_gender_female" id="emp_gender_female">Female</label>

  <br/><br/><br/>

  <label for="emp_local_addr">Local address</label>
  <%= f.text_area :local_addr, :cols => 15, :rows => 5, :maxlength =>'500' %><br/><br/>

  <label for="emp_perm_addr">Permanent address</label>
  <%= f.text_area :perm_addr, :cols => 15, :rows => 5, :maxlength =>'500' %><br/>
  <label for="same_as_local_addr">Same as local addr</label>
  <input id="copy_addr" name="copy_addr" type="checkbox" value="0"/><br><br/>

 
  <label for="employee_mobile">Mobile no</label>
  <%= f.text_field :mob_no, :size=>'15' %><br/><br/>

  <label for="employee_phone">Phone no</label>
  <%= f.text_field :phone_no, :size=>'15' %><br/><br/>


  <label for="employee_pan">PAN no</label>
  <%= f.text_field :pan_no, :size=>'15' %><br/><br/>

  <label for="pers_email_id">Personal email</label>
  <%= f.text_field :pers_email_id, :size=>'15', :maxlength=>'100' %><br/><br/>

</fieldset>

<fieldset id="new_emp_emp_detail">
<%content_for(:page_title, "Employment Details")%>
<h4>Professional Details</h4>

  <label for="employee_id">Emp id</label>
  <%= f.text_field :emp_id, :size=>'15' %><br/><br/>
  
  <label for="employee_designation">Designation</label>
  <%= f.text_field :designation, :size=>'15',:maxlength =>'100' %><br/><br/>

  <label for="employee_doj">Date of joining</label>
  <%= f.date_select :doj, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true,:start_year => 1900, :end_year => Date.today.year %><br/><br/>

  <label for="manager_emp_id">Manager's emp id</label>
  <%= f.text_field :manager_emp_id, :size=>'15' %><br/><br/>

  <label for="manager_name">Manager's name</label>
  <%= f.text_field :manager_name, :size=>'15',:maxlength =>'100' %><br/><br/>


  <label for="off_email_id">RapidThink email</label>
  <%= f.text_field :off_email_id, :size=>'15', :maxlength =>'100' %><br/><br/>

  <% 
      @roles=[]
      @roles.push(['None',0])
      @roles.push(['Admin',1])
      @roles.push(['Leave Approver',2])

  %>

   <label for="roles">Roles</label>
   <%= f.select :roles, options_for_select(@roles, :selected => @roles[0][1], :disabled => @roles[0][1]), {}, {:multiple => true}  %><br/><br/>
  
</fieldset>


<fieldset id="new_emp_leave_detail">
<h4>Joining Leave Credits</h4>
<%=f.fields_for :leaves do |l| %>

<%content_for(:page_title, "Leave Details")%>

  <!--<label for="CL">Casual Leaves</label>-->
  <%=l.select :leave_type, options_for_select([['CL','CL'],['EL','EL'],['SL','SL'],['OH','OH']]) %>
  <%=l.text_field :no_of_days, :size=>'15' %> days <br/><br/>
  <%=l.hidden_field :start_date, :value => Date.today%>
  <%=l.hidden_field :end_date, :value => Date.today%>
  <%=l.hidden_field :admin_comments, :value => 'Initial Credit'%>
  <%=l.hidden_field :action, :value => 'Credit'%>
  <%=l.hidden_field :requester_emp_id%>


<%end%>

<div class="buttons">
	<input type="submit" name="commit" value="Create Employee" class="button_large" tabindex="8"> 
	<!--<input type="reset" name="cancel" value="Cancel" class="button_large" tabindex="9">-->
</div>

</fieldset>


<% end %>

app/views/employees/edit.html.erb
<% content_for(:page_title, "Edit Employee details") %>
<% content_for :emp_sel do %>
<h3>Edit Employee</h3>
<div id="emp_det">
<%=render "edit_employee_details" %>
</div>
<% end %>

app/views/employees/index.html.erb
<% content_for(:page_title, "View Employees") -%>
<% content_for :emp_sel do %>
<div id="rt_emps">
<h3>RapidThink Employees</h3>
<div id="emp_search">
<%= form_tag employees_path, :method => 'get' do %> 
    <%= text_field_tag :search, params[:search] %>
    <input type="submit" value="Search", id="search_button"> 
<% end %>
</div>
<%= render "employees" %>
<%= will_paginate @employees %>
</div>
<% end %>

app/views/employees/leave_balances.html.erb
<% content_for(:page_title, "Check my leave balances") %>
<% content_for :emp_sel do %>
<div id="emp_leaves">
     <h4>Leave balances as on today, <%=Date.today.strftime('%a')-%> <%=Date.today.strftime('%d-%b-%Y')-%>, for <%=session[:user].employee.first_name.capitalize%> <%=session[:user].employee.last_name.capitalize %></h4>
     <table id="emp_det_table" border="1">
      <thead>
        <tr>
         <th>Type</td>
         <th>Count</th>
        </tr>
       </thead>
       <tbody>
        <tr>
         <td>Earned Leave</td>
         <td>100</td>
        </tr>
       <tr>
         <td>Casual Leave</td>
         <td>200</td>
        </tr>
        <tr>
         <td>Sick Leave</td>
         <td>500</td>
        </tr>
         <tr>
         <td>Optional Holiday</td>
         <td>200</td>
        </tr>
       </tbody>
       <tfoot>
        <tr>
         <td>Total</td>
         <td>900</td>
        </tr>
       </tfoot>
      </table>
<div class="disclaimer">
     <span>Note:</span><br/>
     **All unused 'sick' and 'casual' leaves will be lapsed at the end of (31 Mar) current leave year.<br/>
     **All unused 'earned' leaves will be carried forward into next years leave credits.<br/>
<div>
</div>
<% end %>
 

app/views/employees/my_leave_approvals.html.erb
blah blah

app/views/employees/new.html.erb
<% content_for(:page_title, "Create a new employee") %>
<% content_for :emp_sel do %>
<h3>New Employee</h3>
<div id="emp_det">
<%=render "new_employee_details" %>
</div>
<% end %>


    