config/routes.rb
LeaveSystem::Application.routes.draw do
resource :authentication, :controller => "authentication" do
  member do
     match :login
     get :logout
     match :set_password
     match :forgot_password
     match :reset_password
  end
end

resources :employees, :controller => "employees" do
   member do
       put :update
       get :leave_balances
       get :my_leave_approvals
   end

   resources :leaves, :controller => "leaves"
end

end

app/models/leave.rb
class Leave < ActiveRecord::Base
  attr_accessible :action_remarks, :admin_comments, :approver_emp_id, :end_date, :ref_id, :leave_type, :no_of_days,
 :request_remarks, :requester_emp_id, :start_date, :status, :request_remarks,:request_date, :action

validates_presence_of :requester_emp_id
validates_presence_of :leave_type
validates_presence_of :start_date, :end_date, :no_of_days
validates_presence_of :action

validates_numericality_of :requester_emp_id, :only_integer => true, :message => "Please input a valid entry for requester emp id"
#validates_numericality_of :approver_emp_id, :only_integer => true, :message => "Please enter a whole number for approver emp id"
validates_numericality_of :no_of_days, :only_integer => true, :message => "Please enter a whole no for no. of days of leave"
validates_date :start_date, :end_date

belongs_to :employee, :class_name => 'Employee', :foreign_key => 'employee_id'
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
before_filter :login_required
before_filter :find_user_id
before_filter :find_logged_emp

layout 'leave'

def new
 @leave=Leave.new
end

def create
 @leave=Leave.new(params[:leave])
 @leave.end_date = @leave.end_date.strftime("%d-%b-%Y")
 @leave.start_date = @leave.start_date.strftime("%d-%b-%Y")
 @leave.no_of_days = (@leave.end_date - @leave.start_date).to_i + 1
 @leave.requester_emp_id=@emp.emp_id
 @leave.employee_id=@emp.id
 lt=params[:leave][:leave_type]
 lref_id=@leave.ref_id=("LR" + lt.to_s + rand(10 ** 10).to_s.rjust(10,'0')).to_s
 @leave.approver_emp_id=@emp.find_leave_approver.emp_id
                         
 
 if @leave.save
      flash[:notice]="Leave request #{lref_id} was submitted successfully!"
      redirect_to :action => 'new'
  else
      flash[:errors]="(Error creating new leave request, #{@leave.errors})"
      redirect_to :action => 'new'
 end
end

def my_leave_history

end




def find_user_id
    @uid=current_user_id
end
    
def find_logged_emp
    @emp=current_emp
end

end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/leaves/_leave_request_details.html.erb
<fieldset id="leave_req">
<%= form_for :leave, :url => employee_leaves_path  do |f| %>

<label for="leave_start_date">Leave Start Date </label>
<%= f.date_select :start_date, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true, :start_year => (Date.today.year), :end_year => (Date.today.year + 1) %><br/><br/>

<label for="leave_end_date">Leave End Date</label>
<%= f.date_select :end_date, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true, :start_year => (Date.today.year), :end_year => (Date.today.year + 1) %><br/><br/>

<label for="leave_type">Leave Type</label>
<%= f.select :leave_type, options_for_select([["Sick Leave", "SL"], ["Casual Leave", "CL"],["Earned Leave", "EL"], ["Optional Holiday", "OH"]]) %><br/><br/>

<label for="request_remarks">Request Remarks</label>
<%= f.text_area :request_remarks, :cols => "16", :rows => "5" %><br/><br/>

<%=f.hidden_field :action, :value => 'New' %> 
<%=f.hidden_field :request_date, :value => Date.today%>


<div class="submit">
   <%= f.submit 'Request Leaves', :class => 'leave_button' %>
</div>

<% end %>
</fieldset>

app/views/leaves/my_leave_approvals.html.erb
blah blah

app/views/leaves/new.html.erb
<% content_for(:page_title, "New Leave Request") %>
<% content_for :emp_sel do %>
<h3>New Leave Request</h3>
<div id="emp_leave_request">
  <%= render "leave_request_details" %>
</div>
<% end %>