config/routes.rb
LeaveSystem::Application.routes.draw do
resource :authentication, :controller => "authentication" do
  member do
     match :login
     get :logout
     match :set_password
     match :forgot_password
     match :reset_password
  end
end

resources :employees, :controller => "employees" do
   member do
       put :update
       get :leave_balances
       get :my_leave_approvals
   end

   resources :leaves, :controller => "leaves"
end

end

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeaveSystem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="page">
  <div id="header">
     <div id="bannerimg">
       <!--<a href="http://www.rapidthink.com" target="_blank"><%= image_tag "/images/app_header.gif", :alt => "Rapidthink Software Pvt Ltd.", :class => "sys_banner" %></a>-->
     </div>
  </div>
<div id="main">
    <div id="primary">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
</div>
<%= render :partial => "/shared/notices" %>
</body>
</html>

app/views/layouts/_emp_hub.html.erb
<% content_for :content do -%>
<div id="outer">
<div class="left_col">
      <div id="emp_home">
         <%= yield :emp_home %>
     </div>
</div>

<div class="right_col">
  <div id="logout"><%= link_to("Logout", logout_authentication_path) %></div>
  <div id="welcome">Welcome <%=@emp.first_name.capitalize%> </div>
  <div id="reset"><%=link_to("Reset Password", reset_password_authentication_path) %></div>   

   <% if content_for? :emp_sel %>
    <div id="menu_sel">
      <%= yield :emp_sel %>
    </div>
   <% end %>

 </div>

</div>

<% end %>

<%= render :file => 'layouts/_application' %>

app/views/layouts/account.html.erb
<%= render :file => 'layouts/_application' %>

app/views/layouts/authentication.html.erb
<%= render :file => 'layouts/_application' %>

app/views/layouts/employee.html.erb
<% content_for :employee_content do %>
   <div id="employee">
       <%= yield %>
   </div>
<% end %>
<%= render :partial => "/employees/emp_home"%>
    

app/views/layouts/leave.html.erb
<%= render :partial => "/employees/emp_home"%>
    